name: "DEV DEPLOY"

on:
    push:
        branches:
            - develop

permissions:
    id-token: write
    contents: read

jobs:
    terraform:
        uses: ./.github/workflows/terraform.yml
        with: 
            environment: dev
            aws-assume-role-arn: "arn:aws:iam::172977038820:role/github-actions-leosilva1999-pipeline"
            aws-region: "sa-east-1"
            aws-statefile-s3-bucket: "leosilva1999-sa-east-1-terraform-statefile"
            aws-lock-dynamodb-table: "leosilva1999-sa-east-1-terraform-lock"
        secrets:
            DB_PASSWORD: ${{ secrets.DB_PASSWORD }}